# Generated by Django 4.2.1 on 2023-05-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0003_alter_cliente_saldo_alter_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='Talle',
            field=models.IntegerField(help_text='the publisher talle.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='PrecioCompra',
            field=models.FloatField(help_text='the publisher precioCompra.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='PrecioVenta',
            field=models.FloatField(help_text='the publisher PrecioVenta.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Stock',
            field=models.IntegerField(help_text='the publisher stock.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Talle',
            field=models.CharField(choices=[('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='Telefono',
            field=models.IntegerField(help_text='the publisher talle.'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='Telefono',
            field=models.IntegerField(help_text='the publisher talle.'),
        ),
    ]
