# Generated by Django 4.2.1 on 2023-06-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0004_alter_compra_talle_alter_producto_preciocompra_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendedor',
            new_name='Vendedores',
        ),
        migrations.AlterField(
            model_name='compra',
            name='Talle',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Talle',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=50),
        ),
    ]
