# Generated by Django 4.2.1 on 2023-06-07 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0005_rename_vendedor_vendedores_alter_compra_talle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='Producto',
        ),
        migrations.CreateModel(
            name='VentaProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.producto')),
                ('Ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.ventas')),
            ],
        ),
    ]
