# Generated by Django 4.2.2 on 2023-06-22 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoProducto', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Talle', models.CharField(max_length=5)),
                ('Color', models.CharField(max_length=50)),
                ('Marca', models.CharField(max_length=100)),
                ('PrecioCompra', models.FloatField(max_length=10)),
                ('PrecioVenta', models.FloatField(max_length=10)),
                ('Stock',models.IntegerField(max_length=5)),
                
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Telefono', models.IntegerField(max_length=30)),
                ('Localidad', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Telefono', models.IntegerField(max_length=30)),
                ('Direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Telefono', models.IntegerField(max_length=30)),
                ('Direccion', models.CharField(max_length=100)),
                ('Saldo', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miProyecto.producto')),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miProyecto.proveedor')),
                ('Talle', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miProyecto.vendedores')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miProyecto.cliente')),
                ('TipoVenta', models.CharField(max_length=100)),
                ('TipoPago', models.CharField(max_length=100)),
                ('Total', models.FloatField(max_length=10)),
                ('Fecha', models.DateField(max_length=10)),
                
            ],
        ),
        #migrations.AddField(
        #    model_name='cabania',
        #    name='complejo',
        #    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.complejo'),
        #),
    ]